### ISSUE TITLE
Update for downgraded package

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/setup-msys2-gcc#25]
@eregon & @ntkme 

I think I've mentioned that the whole 'system' of creating archives (7z files) is in need of an update.

1. Several years ago Ruby was released with an upgrade from OpenSSL 1.1 to OpenSSL 3, and I made some bad choices then.
2. That problem required 'downgrade' archive packages, and I suspected it would occur again, which has now occurred with gcc.
3. Going forward, this may become more common (build tool/package incompatibility), so I'd like to make it easier to update, and also clearer as to how it works.

So, what I'd like to do is set it up so the package/downgrade info is more 'data/configuration' driven, rather than the current 'code' driven approach.

An example of what I think will be needed is shown below in a new GHA matrix:
```yaml
matrix:
  include:
    # The below jobs have no package downgrades
    - { os: windows-2022  , file: msys2      , ruby: 3.4   }
    - { os: windows-11-arm, file: msys2-arm64, ruby: head  }
    - { os: windows-2022  , file: mingw64    , ruby: mingw }
    - { os: windows-2022  , file: ucrt64     , ruby: ucrt  }
    - { os: windows-11-arm, file: clangarm64 , ruby: head  }
    - { os: windows-2022  , file: mswin      , ruby: mswin }
    # The below jobs have package downgrades, at present, GCC and/or OpenSSL
    # All downgrade packages must be stored in the 'new name' release
    - { os: windows-20222 , file: ucrt64-gcc14        , ruby: 3.2, downgrade: gcc-14.2.0-3 }
    - { os: windows-20222 , file: ucrt64-gcc14-ssl1.1 , ruby: 3.1, downgrade: gcc-14.2.0-3 openssl-1.1.1.w-1 }
    - { os: windows-20222 , file: mingw64-gcc14-ssl1.1, ruby: 3.0, downgrade: gcc-14.2.0-3 openssl-1.1.1.w-1 }
 ```

3. I intend to use a new release for these packages, so the work can be done without affecting current code in `setup-ruby`.
4. One issue is how to push code to `setup-ruby` for the proper selection of which build tool archive files to install, based on the Ruby version and platform. This code may be messy, since patch versions may be needed for proper selection, eg Ruby 3.4.3 should use gcc-14, but Ruby 3.4.4 should use gcc-15 (assuming backports).  I'd like to keep the data here, possibly in a json or yaml format, and transfer it in some way to `setup-ruby`, which is where the selection occurs.

Any thoughts?

@hsbt I'm not sure where to look.  Is there a stated policy regarding backports for updated build tool/package issues?  If they are backported to 'bug' supported versions, would they also be done for Ruby versions in 'security only' updates?  Thanks for adding the Ubuntu gcc-15 CI...

***EDIT:** I have not mentioned.  MSYS2 uses `pacman` for its package manager, and `pacman` only allows one package to be installed. Unlike some other popular package managers, `pacman` will only install one version.  So, to downgrade a package, we need to store the downgrade package (MSYS2 only keeps old packages for a limited time), and use a different install command.

**Comment by ntkme** [comment]
This is the problem of serving the compiler tool chain as part of setup-ruby for users’ convenience. We could have said if you need tool chain run `ridk install` or use `msys2/setup-msys2` action. However, as the community have been relying on this for so long, it’s too late to make this change.

As we will likely continue to provide bundled tool chains, I have a few comments if we actually get a chance to rework this from scratch:

- Do not rely on the preinstalled msys2 in the hosted x64 runners, let’s just install and snapshot a full msys2 inside `c:/hostedtoolcache/windows`. This helps us avoid any possible runner image inconsistency in the future that the delta package may become problematic. It will also improve the compatibility with self-hosted runners. In reality the delta package only saves a few seconds max per run on hosted runners, I think it’s a premature optimization that’s simply not worth it.
- Consider bundle windows ruby and msys2 as a single package by pre-running the setup in ruby/ruby-builder. If user choose to not have the tool chain, we can still download the same package, just skip adding msys2 to PATH. By providing a single package of preinstalled ruby and msys2, it would also allow us to effectively have an “immutable” msys2 snapshot that is tied to each ruby release. The downside is that users won’t get any updates automatically (especially security updates to OpenSSL), that we will have to manually update the “immutable” snapshots for all users every time. However, the upside is that because it’s effectively a frozen environment it won’t have regression caused by upgrades. One more thing is that it simplifies the situation that you won’t need to have a mapping of what version of toolchain tool chain to download for which ruby maintained in setup-ruby.

**Comment by eregon** [comment]
The proposed names LGTM.

> 4\. I'd like to keep the data here, possibly in a json or yaml format, and transfer it in some way to `setup-ruby`, which is where the selection occurs.

Yes, JSON would be fine. It could also be code as a `.js` file without dependencies (or only well-known ones like actions toolkit `core`, but a bit dangerous as we could have different versions of that package).
Either way we could copy the file from this repo to setup-ruby every time it's needed.
I'm also OK with just a snippet of code/a function we copy to setup-ruby and mention where it comes from.

> * In reality the delta package only saves a few seconds max per run on hosted runners, I think it’s a premature optimization that’s simply not worth it.

I don't recall the exact numbers but extraction is unfortunately very slow on Windows (downloading is fast), picking for example https://github.com/ruby/setup-ruby/actions/runs/14765135437/job/41454925639?pr=761#step:3:26 gives:
Extracting  msys2 build tools
Took  45.18 seconds
Extracting  ucrt64-3.0 build tools
Took  35.48 seconds

I don't know if that one is incremental or not, but yeah the motivation for "just download the delta" is to speedup that.
It'd be good to have some numbers to compare, adding a few seconds when it already takes over a minute is probably fine, but adding something like a minute seems not so good.

I agree though in principle it would be simpler and safer to ignore any preinstalled msys2. Though could that cause problems if two msys2 installations exist, especially if one is in a standard location and we might end up using a mix of both?
Is the preinstalled msys2 on PATH?

> * Consider bundle windows ruby and msys2 as a single package by pre-running the setup in ruby/ruby-builder.

Interesting. Where would we store such bundled ruby + toolchain? Here maybe?
One thing is I don't want to handle building or rebuilding those, because I know too little about Windows, and I don't like rebuilding releases (doing so in ruby-builder for non-Windows is a pain).
I think this approach is only viable if we very very rarely need to rebuild. Not sure whether that's the case (e.g., over time C extensions might expect a newer compiler/C standard, or another thought is Visual Studio compilers seem to have frequent bugs (from what I see on https://bugs.ruby-lang.org/) and so staying on an old version might not be feasible, though Visual Studio is no concern here I suppose we use the one from the image).

**Comment by ntkme** [comment]
> I don't recall the exact numbers but extraction is unfortunately very slow on Windows

Unfortunately, this is a result of weak x64 hardware on default hosted runners. - if you look at windows-11-arm runners which currently download a full msys2 package we built from scratch, the extraction is less than 15 seconds (roughly 3x faster) with the 7z archive being twice as large.

If download is fast, but decompression is a performance concern due to weak hardware, a simple optimization can be reduce compression ratio or use archive without compression. Download size will increase but extraction will be much faster. Also keep in mind that executable files in general doesn’t compress that well, for an archive that the majority of the size are binaries, it’s probably better use a plain archive with compression rate 0 (e.g. something equivalent to a plain tar file without compression).

One thing that I need to test is that whether the slowness of compression is due to weak CPU or weak disk I/O. - If it’s weak CPU than the no compression optimization is worth doing, but if it’s weak disk I/O then not much we can do.

**Comment by ntkme** [comment]
I did a quick benchmark... The issue is weak disk I/O on `C:` drive on x64 runners. - If we extract the same archive to `D:` drive it's about 5 times faster - so even if we have 2x archive size that's still about 3x faster (you can compare the msys2.7z vs msys2-arm.7z time).

The annoying inconsistency is that x64 runner has a slow `C:` and a fast `D:`, but arm64 runner only has a fast `C:`.

``` yaml
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022, windows-2025, windows-11-arm]
        archive: [msys2, msys2-arm64]
        destination: [C:\msys2, D:\msys2]
        exclude:
          - os: windows-11-arm
            destination:  D:\msys2
    steps:
      - name: Download ${{ matrix.archive }}.7z
        run: |
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/ruby/setup-msys2-gcc/releases/download/msys2-gcc-pkgs/${{ matrix.archive }}.7z", "${{ matrix.archive }}.7z")
      - name: Extract ${{ matrix.archive }}.7z to ${{ matrix.destination }}
        run: |
          7z x ${{ matrix.archive }}.7z -o${{ matrix.destination }}
```
